config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :products, only: [ :index, :show, :edit, :destroy, :update ] do
    resources :bookings, only: [ :create, :new ]
    resources :reviews, only: [ :new, :create ]
  end

  resources :bookings, only: [ :destroy, :show, :edit, :update ]
  resources :users do
    resources :products, only: [ :create, :new]
  end
  resource :dashboard, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validate :end_date_after_start_date
  before_create :set_total_price

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, 'must not be before start date')
    end
  end

  def duration
    (end_date - start_date).to_i
  end

  def set_total_price
    total_price = product.price_per_day * duration
    return total_price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description, :address],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :bookings
  has_many :reviews
  has_many :received_bookings, through: :products, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?
    include Pundit
    # Pundit: white-list approach.
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
  
      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address])
    end
  
    private
  
    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = Booking.new
    @product = Product.find(params[:product_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @product = Product.find(params[:product_id])
    @user = current_user
    @booking.product = @product
    @booking.user = @user
    @booking.status = "pending"
    authorize @booking
    if @booking.save
      redirect_to @booking
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = params[:status]
    @booking.save
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized, only: :show
  after_action :verify_policy_scoped, only: :show

  def show
    @applied_bookings = policy_scope(current_user.bookings).order(created_at: :desc)
    @received_bookings = policy_scope(current_user.received_bookings).order(created_at: :desc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = policy_scope(Product).order(created_at: :desc)

    if params[:query].present?
      @products = Product.search_by_name_and_description(params[:query])
    else
      @product = Product.all
    end

    @markers = @products.geocoded.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        info_window: render_to_string(partial: "info_window", locals: { product: product })
      }
    end
  end

  def show
    @product = Product.find(params[:id])
    authorize @product
    @booking = Booking.new
  end

  def new
    @product = Product.new
    @user    = current_user
    @review  = Review.new 
    authorize @product
  end

  def create
    @product      = Product.new(strong_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
    authorize @product
  end

  def edit
    @product      = Product.find(params[:id])
    # @product.user = current_user
    authorize @product
  end

  def update
    @product = Product.find(params[:id])
    authorize @product
    # @product.update(strong_params)
    # @product.save
    if @product.update(strong_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product      = Product.find(params[:id])
    @product.user = current_user
    @product.delete

    authorize @product
    redirect_to products_path
  end

  private

  def strong_params

    params.require(:product).permit(:name, :description, :address, :price_per_day, :latitude, :longitude, :photo)

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @product = Product.find(params[:product_id])
        @review = Review.new
        authorize @review
    end
    def create
        @product = Product.find(params[:product_id])
        @review = Review.new(review_params)
        @review.product = @product
        @review.user= current_user
        authorize @review
        respond_to do |format|
            if @review.save
              format.html { redirect_to product_path(@product, anchor: "#review-#{@review.id}") }
              format.json
            else 
                format.html { render 'product/show'}
                format.json
            end        
        end
    end

    private

    def review_params
    params.require(:review).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        # retrive information about user
        @user = current_user
        # show boookings dates
        @user.booking_id = @bookings
        # show total price
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class = "container">
    <%= simple_form_for [ @product, @booking ] do |f| %>
      <%= f.input :start_date, as: :date %>
      <%= f.input :end_date, as: :date %>
      <div class="form-actions">
        <%= f.submit "Edit", class: "btn btn-warning my-3" %>
      </div>
    <% end %>
    <%= link_to "back to main page", products_path %>
</div>

app/views/bookings/new.html.erb
<div id="formContent" class="container">
<h1>booking table</h1>
  <div class="wrapper fadeInDown">
    <div class="form-inputs">
      <%= simple_form_for [ @product, @booking ] do |f| %>
        <%= f.input :start_date, as: :date %>
        <%= f.input :end_date, as: :date %>
        <div class="form-actions">
          <%= f.submit "Book Now", class: "btn btn-warning my-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class = "container">

    <h1>your booking detail</h1>
    <p>
       <p><strong> Product Name</strong></p> <%= @booking.product.name %>
    </p>
    <hr>
    <p>
        <p><strong> Product Address</strong></p><%= @booking.product.address %>
    </p>
    <hr>
    <p>
        <p><strong> Total Price</strong></p> <%= @booking.total_price %>
    </p>
    <%= link_to "back to main page", products_path %>
</div>

app/views/dashboards/show.html.erb
<div class="container">
  <% @received_bookings.each do |rb| %>
  <div class="booking-card">
    <p><%= rb.product.name %>, <%= rb.product.address %>, <%= rb.start_date %> - <%= rb.end_date %></p>
    <% if rb.status == "pending" %>
      <% if policy(rb).update? %>
        <%= link_to "accept", booking_path(rb, {status: "accepted"}), method: :patch, class: "accept-update-button"%>
        <%= link_to "reject", booking_path(rb, {status: "rejected"}), method: :patch, class: "reject-update-button"%>
      <% end %>
      <% elsif rb.status == "accepted"%>
        <div class="already_accepted"><p> It's been accepted already </p></div>
      <% else %>
        <div class="already_rejected"><p> It's been rejected </p></div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HeadphoneBNB</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <%= render '/shared/navbar' %>
  <% if notice || alert %>
    <p class="notice alert-info"><%= notice %></p>
    <p class="alert alert-warning"><%= alert %></p>
  <% end %>
  <%= yield %>

  <%= render 'shared/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'headphone_background.jpeg' %>);">
  <div class="container">
    <div class="row justify-content-center text-center">
      <div class="col-6">
        <h1>Lost your headphones?</h1>
        <h1>Need new headphones?</h1>
        <p>Join HEADPHONE BNB to rent headphones near you!</p>
      </div>
    </div>
    <div class="row">
      <div class="col text-center">
        <% if user_signed_in? %>
          <a class="btn btn-light" href="/products">Go to Index</a>
        <% else %>
          <a class="btn btn-light" href="/users/sign_up">Sign up</a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_info_window.html.erb
<h2><%= product.name %></h2>
<p><%= product.price_per_day %> € / per day</p>

app/views/products/_review.html.erb
<p id="review-<%= review.id %>"><%= review.content %></p>

app/views/products/edit.html.erb
<%= render "shared/form", product: @product %>

app/views/products/index.html.erb
<div class="search-container"><%= form_tag products_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find Headphones"
  %>
  <%= submit_tag "Search", class: "btn btn-primary search-button" %>
<% end %>
</div>
<div class="album py-5 bg-light shadow-lg rounded">
  <%# <div class="container"> %>
    <div class="row">
      <div class="col-8">
        <%# <div class="container"> %>
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <% @products.each do |product| %>
              <div class="col mb-3">
                <div class="card shadow-sm">
                  <div class="col-auto d-none d-lg-block">
                    <%= cl_image_tag(product.picture_url, :class => "card-img-top", :width => 100) %>
                  </div>
                  <div class="card-body">
                    <h3 class="card-title text-center"><%= product.name %></h3>
                    <%# <p class="card-text"><%= product.description</p> %>
                  </div>


                  <div class="card-footer d-flex justify-content-between align-items-center ">
                    <div class="btn-group">
                      <%= link_to "details", product_path(product), class: "btn btn-outline-secondary" %>
                    </div>
                    <div>
                      <div class="text-muted"><strong><%= product.price_per_day %> € / per day</strong></div>

                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <%# </div> %>
      </div>
      <div class="col-4">
        <div class="img-fluid shadow-lg rounded"
            id="map"
            style="width: 100%; height: 80vh; position: sticky; top: 0"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  <%# </div> %>
</div>

              <%# <% <img src="<%= product.picture_url" class="card-img-top"> %>

app/views/products/new.html.erb
<div id="formContent" class="container">
  <div class="wrapper fadeInDown">
    <div class="form-inputs">
      <%= simple_form_for [ @user, @product ]  do |f| %>
        <%= f.input :name, input_html: { class: "m-2" } %>
        <%= f.input :description, input_html: { class: "mb-3" } %>
        <%= f.input :price_per_day, input_html: { class: "mb-3" } %>
        <%= f.input :address, input_html: { class: "mb-4" } %>
        <%= f.input :photo, as: :file, input_html: { class: "mb-4" } %>
        <div class="form-actions">
          <%= f.submit "Submit your product", class: "btn btn-warning my-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row mt-4">

    <div class=" col-8 card text-center shadow-lg rounded">
      <div class="card-body ">
        <%= cl_image_tag(@product.picture_url, :class => "img-fluid") %>
        <h3 class="card-title"><%= @product.name %></h3>
        <p class="card-text"><%= @product.description %></p>
        <h4><%= @product.price_per_day %> €/per day</h4>
        <div class="d-grid gap-2">
          <%= link_to "Book",  new_product_booking_path(@product), class: "btn btn-secondary" %>
        </div>
      </div>
      <div class="card-footer text-muted d-flex justify-content-end">
        <div class="btn-group">
          <%= link_to "Edit", edit_product_path(@product), class: "btn btn-outline-secondary mx-3" %>
          <%= link_to "Delete",
                      product_path(@product),
                      class:  "btn btn-outline-warning",
                      method: :delete,
                      data:   { confirm: "Are you sure?" } %>
        </div>
      </div>
    </div>
    <div class = "col-4 card shadow-lg rounded" data-controller="insert-in-list">
      <div class = "card-body">
        <div class = "h4"><strong> Reviews </strong> </div>
        <hr>
        <div id="reviews" data-insert-in-list-target = "items" >
          <% if @product.reviews.blank? %>
            Be the first to leave a review for <%= @product.name %>
          <% else %>
            <% @product.reviews.each do |review| %>
              <%= render 'review', review: review  %>
              <hr>
            <% end %>
          <% end %>
        </div>
        <%= render 'reviews/form', restaurant: @restaurant, review: @review %>
      </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([ @product, Review.new ], data: { insert_in_list_target: "form",
                                                action: 'submit->insert-in-list#send' }) do |f| %>
    <%= f.input :content %>
    <%= f.button :submit, class: "btn-outline-secondary mx-3" %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
      </ul>
      <p class="text-center text-muted">© <%= Time.now.year %> Team FixJet </p>
    </footer>
  </div>
</div>

app/views/shared/_form.html.erb
<div id="formContent" class="container">
  <div class="wrapper fadeInDown">
    <div class="form-inputs">
      <%= simple_form_for [ @user, @product ]  do |f| %>
        <%= f.input :name, input_html: { class: "m-2" } %>
        <%= f.input :description, input_html: { class: "mb-3" } %>
        <%= f.input :price_per_day, input_html: { class: "mb-3" } %>
        <%= f.input :address, input_html: { class: "mb-4" } %>
        <%= f.input :photo, as: :file %>
        <div class="form-actions">
          <%= f.submit "Submit your product", class: "btn btn-warning my-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to products_path, class: "navbar-brand" do %>
      <%= image_tag "headphone_logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Create product", new_user_product_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to dashboard_path do %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/arman-aminzadeh", class: "avatar" %>
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>